### PR TITLE
gofmt -s

### PR DESCRIPTION
**Pull request by shawnps**

### CODE REVIEW

**Comment by shurcooL** [comment]
The changes in this PR LGTM.

**Comment by buro9** [comment]
I'm going to decline this.

The vast majority of people (a quick survey of the plugins for editors and the Go engineers at work) use gofmt without args and the whole point is to have everyone use the same settings. If these changes were merged than anyone contributing would have to change their settings or manually apply a gofmt -s prior to commit.

**Comment by shurcooL** [comment]
> If these changes were merged than anyone contributing would have to change their settings or manually apply a gofmt -s prior to commit.

@buro9, that not correct, you misunderstand the effect of using `gofmt -s`.

`gofmt -s` applies normal gofmt formatting, and also simplifies Go code where possible:

```
-s
	Try to simplify code (after applying the rewrite rule, if any).
```

Both the original and simplified Go code are valid, gofmted code. The simplified version simply omits some unneeded verbosity. But it is not incompatible with normal gofmt formatting rules.

That means all future contributors, even if they don't use `-s` option, will not revert the change that `-s` created.

It's equally possible to write Go code by hand that is already "simple" such that `gofmt -s` will have no effect. Most Go code is like that, that's why `gofmt -s` rarely produces a diff.

**Comment by shawnps** [comment]
yup, agree with @shurcooL, seems really redundant to declare `test` in all of those structs. No big deal though.

**Pull request closed without merging**
